# Generated by Django 2.2 on 2020-11-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='person',
            new_name='church',
        ),
    ]
