# Generated by Django 2.2 on 2020-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0003_auto_20201116_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastor_name', models.CharField(max_length=255)),
                ('pastor_title', models.CharField(max_length=255)),
                ('pastor_phone', models.CharField(max_length=13)),
                ('pastor_email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='church',
            name='address',
            field=models.CharField(default='whatever', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='church_email',
            field=models.CharField(default='test@test.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='church_phone',
            field=models.CharField(default='0000000000', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='city_state',
            field=models.CharField(default='null, null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='denomination',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='facebook',
            field=models.CharField(default='facebook', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='instagram',
            field=models.CharField(default='instagram', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='twitter',
            field=models.CharField(default='twitter', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='values',
            field=models.TextField(default='values'),
            preserve_default=False,
        ),
    ]
