# Generated by Django 2.2 on 2020-11-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0004_auto_20201118_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastor',
            name='pastor_social',
            field=models.CharField(default='social', max_length=255),
            preserve_default=False,
        ),
    ]
