# Generated by Django 2.2 on 2020-11-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0005_pastor_pastor_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='website',
            field=models.CharField(default='jesus.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pastor',
            name='church',
            field=models.ManyToManyField(related_name='church_pastor', to='church_app.Church'),
        ),
    ]
