# Generated by Django 2.2 on 2020-11-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0006_auto_20201118_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='old',
            field=models.CharField(default='10', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='oldest',
            field=models.CharField(default='10', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='other',
            field=models.TextField(default='We are the best'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='size',
            field=models.CharField(default='500', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='young',
            field=models.CharField(default='20', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='younger',
            field=models.CharField(default='30', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='youngest',
            field=models.CharField(default='20', max_length=255),
            preserve_default=False,
        ),
    ]
