# Generated by Django 2.2 on 2021-01-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0008_remove_church_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prof_picture',
            field=models.ImageField(default='picture.jpg', upload_to='imgs/'),
            preserve_default=False,
        ),
    ]
