# Generated by Django 2.2 on 2020-11-23 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0010_usercomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='baptist',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='catholic',
            field=models.CharField(default='catholic', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='church_size',
            field=models.CharField(default='0-100', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.TextField(default='Single'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lutheran',
            field=models.CharField(default='Lutheran', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='methodist',
            field=models.CharField(default='yes', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='no_preference',
            field=models.CharField(default='no preference', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nondenominational',
            field=models.CharField(default='non Denominational', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='other',
            field=models.CharField(default='other', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pentecostal',
            field=models.CharField(default='pentecostal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='reformed',
            field=models.CharField(default='reformed', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='small_groups',
            field=models.CharField(default='50', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='student_programs',
            field=models.CharField(default='50', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.CharField(default='111 St', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_city_state',
            field=models.CharField(default='Northville, MI', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default='email@email.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_facebook',
            field=models.CharField(default='facebook.com/facebook', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_instagram',
            field=models.CharField(default='@church', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_other',
            field=models.TextField(default='More info about User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default='0000000000', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_twitter',
            field=models.CharField(default='@user_twitter', max_length=255),
            preserve_default=False,
        ),
    ]
