# Generated by Django 2.2 on 2020-11-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0012_auto_20201123_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_other',
            new_name='user_info_other',
        ),
    ]
