# Generated by Django 2.2 on 2020-12-01 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0013_auto_20201123_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to='church_app.User')),
            ],
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='ChurchMessage',
        ),
        migrations.RemoveField(
            model_name='usercomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercomments',
            name='wall_message',
        ),
        migrations.DeleteModel(
            name='ChurchComments',
        ),
        migrations.DeleteModel(
            name='UserComments',
        ),
    ]
