# Generated by Django 2.2 on 2020-12-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0014_auto_20201201_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_Img',
            field=models.ImageField(default='img', upload_to='images/'),
            preserve_default=False,
        ),
    ]
