# Generated by Django 2.2 on 2020-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0017_auto_20201204_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='city_state',
            new_name='church_city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_city_state',
            new_name='user_city',
        ),
        migrations.AddField(
            model_name='church',
            name='church_state',
            field=models.CharField(default='MI', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.CharField(default='MI', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='family',
            field=models.CharField(max_length=255),
        ),
    ]
