# Generated by Django 2.2 on 2020-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0018_auto_20201204_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='family',
            new_name='adults',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_twitter',
            new_name='kids',
        ),
        migrations.AddField(
            model_name='user',
            name='teens',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
